// Code generated by MockGen. DO NOT EDIT.
// Source: http_client.go
//
// Generated by this command:
//
//	mockgen -source=http_client.go -destination=mocks/http_client_mock.go
//

// Package mock_http is a generated GoMock package.
package mock_http

import (
	http "net/http"
	reflect "reflect"

	jfroghttpclient "github.com/jfrog/jfrog-client-go/http/jfroghttpclient"
	gomock "go.uber.org/mock/gomock"
)

// MockApptrustHttpClient is a mock of ApptrustHttpClient interface.
type MockApptrustHttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockApptrustHttpClientMockRecorder
	isgomock struct{}
}

// MockApptrustHttpClientMockRecorder is the mock recorder for MockApptrustHttpClient.
type MockApptrustHttpClientMockRecorder struct {
	mock *MockApptrustHttpClient
}

// NewMockApptrustHttpClient creates a new mock instance.
func NewMockApptrustHttpClient(ctrl *gomock.Controller) *MockApptrustHttpClient {
	mock := &MockApptrustHttpClient{ctrl: ctrl}
	mock.recorder = &MockApptrustHttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApptrustHttpClient) EXPECT() *MockApptrustHttpClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockApptrustHttpClient) Delete(path string, params map[string]string) (*http.Response, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", path, params)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Delete indicates an expected call of Delete.
func (mr *MockApptrustHttpClientMockRecorder) Delete(path, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApptrustHttpClient)(nil).Delete), path, params)
}

// Get mocks base method.
func (m *MockApptrustHttpClient) Get(path string) (*http.Response, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", path)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockApptrustHttpClientMockRecorder) Get(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApptrustHttpClient)(nil).Get), path)
}

// GetHttpClient mocks base method.
func (m *MockApptrustHttpClient) GetHttpClient() *jfroghttpclient.JfrogHttpClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHttpClient")
	ret0, _ := ret[0].(*jfroghttpclient.JfrogHttpClient)
	return ret0
}

// GetHttpClient indicates an expected call of GetHttpClient.
func (mr *MockApptrustHttpClientMockRecorder) GetHttpClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHttpClient", reflect.TypeOf((*MockApptrustHttpClient)(nil).GetHttpClient))
}

// Patch mocks base method.
func (m *MockApptrustHttpClient) Patch(path string, requestBody any) (*http.Response, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", path, requestBody)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Patch indicates an expected call of Patch.
func (mr *MockApptrustHttpClientMockRecorder) Patch(path, requestBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockApptrustHttpClient)(nil).Patch), path, requestBody)
}

// Post mocks base method.
func (m *MockApptrustHttpClient) Post(path string, requestBody any, params map[string]string) (*http.Response, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", path, requestBody, params)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Post indicates an expected call of Post.
func (mr *MockApptrustHttpClientMockRecorder) Post(path, requestBody, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockApptrustHttpClient)(nil).Post), path, requestBody, params)
}
