// Code generated by MockGen. DO NOT EDIT.
// Source: system_service.go
//
// Generated by this command:
//
//	mockgen -source=system_service.go -destination=mocks/system_service_mock.go
//

// Package mock_systems is a generated GoMock package.
package mock_systems

import (
	reflect "reflect"

	service "github.com/jfrog/jfrog-cli-application/apptrust/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSystemService is a mock of SystemService interface.
type MockSystemService struct {
	ctrl     *gomock.Controller
	recorder *MockSystemServiceMockRecorder
	isgomock struct{}
}

// MockSystemServiceMockRecorder is the mock recorder for MockSystemService.
type MockSystemServiceMockRecorder struct {
	mock *MockSystemService
}

// NewMockSystemService creates a new mock instance.
func NewMockSystemService(ctrl *gomock.Controller) *MockSystemService {
	mock := &MockSystemService{ctrl: ctrl}
	mock.recorder = &MockSystemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemService) EXPECT() *MockSystemServiceMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockSystemService) Ping(ctx service.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSystemServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSystemService)(nil).Ping), ctx)
}
