// Code generated by MockGen. DO NOT EDIT.
// Source: ping_cmd.go
//
// Generated by this command:
//
//	mockgen -source=ping_cmd.go -destination=mocks/ping_cmd_mock.go
//

// Package mock_system is a generated GoMock package.
package mock_system
