// Code generated by MockGen. DO NOT EDIT.
// Source: application_service.go
//
// Generated by this command:
//
//	mockgen -source=application_service.go -destination=mocks/application_service_mock.go
//

// Package mock_applications is a generated GoMock package.
package mock_applications

import (
	reflect "reflect"

	model "github.com/jfrog/jfrog-cli-application/apptrust/model"
	service "github.com/jfrog/jfrog-cli-application/apptrust/service"
	gomock "go.uber.org/mock/gomock"
)

// MockApplicationService is a mock of ApplicationService interface.
type MockApplicationService struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationServiceMockRecorder
	isgomock struct{}
}

// MockApplicationServiceMockRecorder is the mock recorder for MockApplicationService.
type MockApplicationServiceMockRecorder struct {
	mock *MockApplicationService
}

// NewMockApplicationService creates a new mock instance.
func NewMockApplicationService(ctrl *gomock.Controller) *MockApplicationService {
	mock := &MockApplicationService{ctrl: ctrl}
	mock.recorder = &MockApplicationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationService) EXPECT() *MockApplicationServiceMockRecorder {
	return m.recorder
}

// CreateApplication mocks base method.
func (m *MockApplicationService) CreateApplication(ctx service.Context, requestBody *model.AppDescriptor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplication", ctx, requestBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApplication indicates an expected call of CreateApplication.
func (mr *MockApplicationServiceMockRecorder) CreateApplication(ctx, requestBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplication", reflect.TypeOf((*MockApplicationService)(nil).CreateApplication), ctx, requestBody)
}

// DeleteApplication mocks base method.
func (m *MockApplicationService) DeleteApplication(ctx service.Context, applicationKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApplication", ctx, applicationKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApplication indicates an expected call of DeleteApplication.
func (mr *MockApplicationServiceMockRecorder) DeleteApplication(ctx, applicationKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApplication", reflect.TypeOf((*MockApplicationService)(nil).DeleteApplication), ctx, applicationKey)
}

// UpdateApplication mocks base method.
func (m *MockApplicationService) UpdateApplication(ctx service.Context, requestBody *model.AppDescriptor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateApplication", ctx, requestBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateApplication indicates an expected call of UpdateApplication.
func (mr *MockApplicationServiceMockRecorder) UpdateApplication(ctx, requestBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApplication", reflect.TypeOf((*MockApplicationService)(nil).UpdateApplication), ctx, requestBody)
}
