// Code generated by MockGen. DO NOT EDIT.
// Source: promote_app_version_cmd.go
//
// Generated by this command:
//
//	mockgen -source=promote_app_version_cmd.go -destination=mocks/promote_app_version_cmd_mock.go
//

// Package mock_version is a generated GoMock package.
package mock_version
