// Code generated by MockGen. DO NOT EDIT.
// Source: version_service.go
//
// Generated by this command:
//
//	mockgen -source=version_service.go -destination=mocks/version_service_mock.go
//

// Package mock_versions is a generated GoMock package.
package mock_versions

import (
	reflect "reflect"

	model "github.com/jfrog/jfrog-cli-application/apptrust/model"
	service "github.com/jfrog/jfrog-cli-application/apptrust/service"
	gomock "go.uber.org/mock/gomock"
)

// MockVersionService is a mock of VersionService interface.
type MockVersionService struct {
	ctrl     *gomock.Controller
	recorder *MockVersionServiceMockRecorder
	isgomock struct{}
}

// MockVersionServiceMockRecorder is the mock recorder for MockVersionService.
type MockVersionServiceMockRecorder struct {
	mock *MockVersionService
}

// NewMockVersionService creates a new mock instance.
func NewMockVersionService(ctrl *gomock.Controller) *MockVersionService {
	mock := &MockVersionService{ctrl: ctrl}
	mock.recorder = &MockVersionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionService) EXPECT() *MockVersionServiceMockRecorder {
	return m.recorder
}

// CreateAppVersion mocks base method.
func (m *MockVersionService) CreateAppVersion(ctx service.Context, request *model.CreateAppVersionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppVersion", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAppVersion indicates an expected call of CreateAppVersion.
func (mr *MockVersionServiceMockRecorder) CreateAppVersion(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppVersion", reflect.TypeOf((*MockVersionService)(nil).CreateAppVersion), ctx, request)
}

// DeleteAppVersion mocks base method.
func (m *MockVersionService) DeleteAppVersion(ctx service.Context, applicationKey, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAppVersion", ctx, applicationKey, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAppVersion indicates an expected call of DeleteAppVersion.
func (mr *MockVersionServiceMockRecorder) DeleteAppVersion(ctx, applicationKey, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAppVersion", reflect.TypeOf((*MockVersionService)(nil).DeleteAppVersion), ctx, applicationKey, version)
}

// PromoteAppVersion mocks base method.
func (m *MockVersionService) PromoteAppVersion(ctx service.Context, applicationKey, version string, payload *model.PromoteAppVersionRequest, sync bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteAppVersion", ctx, applicationKey, version, payload, sync)
	ret0, _ := ret[0].(error)
	return ret0
}

// PromoteAppVersion indicates an expected call of PromoteAppVersion.
func (mr *MockVersionServiceMockRecorder) PromoteAppVersion(ctx, applicationKey, version, payload, sync any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteAppVersion", reflect.TypeOf((*MockVersionService)(nil).PromoteAppVersion), ctx, applicationKey, version, payload, sync)
}

// ReleaseAppVersion mocks base method.
func (m *MockVersionService) ReleaseAppVersion(ctx service.Context, applicationKey, version string, request *model.ReleaseAppVersionRequest, sync bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseAppVersion", ctx, applicationKey, version, request, sync)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseAppVersion indicates an expected call of ReleaseAppVersion.
func (mr *MockVersionServiceMockRecorder) ReleaseAppVersion(ctx, applicationKey, version, request, sync any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseAppVersion", reflect.TypeOf((*MockVersionService)(nil).ReleaseAppVersion), ctx, applicationKey, version, request, sync)
}

// RollbackAppVersion mocks base method.
func (m *MockVersionService) RollbackAppVersion(ctx service.Context, applicationKey, version string, request *model.RollbackAppVersionRequest, sync bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackAppVersion", ctx, applicationKey, version, request, sync)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackAppVersion indicates an expected call of RollbackAppVersion.
func (mr *MockVersionServiceMockRecorder) RollbackAppVersion(ctx, applicationKey, version, request, sync any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackAppVersion", reflect.TypeOf((*MockVersionService)(nil).RollbackAppVersion), ctx, applicationKey, version, request, sync)
}

// UpdateAppVersion mocks base method.
func (m *MockVersionService) UpdateAppVersion(ctx service.Context, applicationKey, version string, request *model.UpdateAppVersionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppVersion", ctx, applicationKey, version, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppVersion indicates an expected call of UpdateAppVersion.
func (mr *MockVersionServiceMockRecorder) UpdateAppVersion(ctx, applicationKey, version, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppVersion", reflect.TypeOf((*MockVersionService)(nil).UpdateAppVersion), ctx, applicationKey, version, request)
}
