// Code generated by MockGen. DO NOT EDIT.
// Source: context.go
//
// Generated by this command:
//
//	mockgen -source=context.go -destination=mocks/context_mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	http "github.com/jfrog/jfrog-cli-application/apptrust/http"
	config "github.com/jfrog/jfrog-cli-core/v2/utils/config"
	gomock "go.uber.org/mock/gomock"
)

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
	isgomock struct{}
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// GetHttpClient mocks base method.
func (m *MockContext) GetHttpClient() http.ApptrustHttpClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHttpClient")
	ret0, _ := ret[0].(http.ApptrustHttpClient)
	return ret0
}

// GetHttpClient indicates an expected call of GetHttpClient.
func (mr *MockContextMockRecorder) GetHttpClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHttpClient", reflect.TypeOf((*MockContext)(nil).GetHttpClient))
}

// GetServerDetails mocks base method.
func (m *MockContext) GetServerDetails() config.ServerDetails {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerDetails")
	ret0, _ := ret[0].(config.ServerDetails)
	return ret0
}

// GetServerDetails indicates an expected call of GetServerDetails.
func (mr *MockContextMockRecorder) GetServerDetails() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerDetails", reflect.TypeOf((*MockContext)(nil).GetServerDetails))
}
