// Code generated by MockGen. DO NOT EDIT.
// Source: package_service.go
//
// Generated by this command:
//
//	mockgen -source=package_service.go -destination=mocks/package_service_mock.go
//

// Package mock_packages is a generated GoMock package.
package mock_packages

import (
	reflect "reflect"

	model "github.com/jfrog/jfrog-cli-application/apptrust/model"
	service "github.com/jfrog/jfrog-cli-application/apptrust/service"
	gomock "go.uber.org/mock/gomock"
)

// MockPackageService is a mock of PackageService interface.
type MockPackageService struct {
	ctrl     *gomock.Controller
	recorder *MockPackageServiceMockRecorder
	isgomock struct{}
}

// MockPackageServiceMockRecorder is the mock recorder for MockPackageService.
type MockPackageServiceMockRecorder struct {
	mock *MockPackageService
}

// NewMockPackageService creates a new mock instance.
func NewMockPackageService(ctrl *gomock.Controller) *MockPackageService {
	mock := &MockPackageService{ctrl: ctrl}
	mock.recorder = &MockPackageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackageService) EXPECT() *MockPackageServiceMockRecorder {
	return m.recorder
}

// BindPackage mocks base method.
func (m *MockPackageService) BindPackage(ctx service.Context, applicationKey string, request *model.BindPackageRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindPackage", ctx, applicationKey, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindPackage indicates an expected call of BindPackage.
func (mr *MockPackageServiceMockRecorder) BindPackage(ctx, applicationKey, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindPackage", reflect.TypeOf((*MockPackageService)(nil).BindPackage), ctx, applicationKey, request)
}

// UnbindPackage mocks base method.
func (m *MockPackageService) UnbindPackage(ctx service.Context, applicationKey, pkgType, pkgName, pkgVersion string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbindPackage", ctx, applicationKey, pkgType, pkgName, pkgVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbindPackage indicates an expected call of UnbindPackage.
func (mr *MockPackageServiceMockRecorder) UnbindPackage(ctx, applicationKey, pkgType, pkgName, pkgVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbindPackage", reflect.TypeOf((*MockPackageService)(nil).UnbindPackage), ctx, applicationKey, pkgType, pkgName, pkgVersion)
}
